# Generated by Django 5.2.12 on 2026-03-15 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loanrepayment_profile_repaymentvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('DEPOSIT_CREATED', 'Deposit Created'), ('LOAN_REQUESTED', 'Loan Requested'), ('LOAN_VOTED', 'Loan Voted'), ('LOAN_STATUS_CHANGED', 'Loan Status Changed'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_VOTED', 'Investment Voted'), ('INVESTMENT_STATUS_CHANGED', 'Investment Status Changed')], max_length=30),
        ),
        migrations.CreateModel(
            name='InvestmentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invest_to', models.CharField(max_length=120)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invested_on', models.DateField()),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('percentage_snapshot', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.investmentdecision')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('investment', 'voter')},
            },
        ),
    ]
